AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: サーバレステスト自動化プロジェクト - 時刻変換と日付計算

Resources:
  # Lambda関数の定義
  ConvertToJSTFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/convertToJST/
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 10
      MemorySize: 128

  CalculateTimeDifferenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/calculateTimeDifference/
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 10
      MemorySize: 128

  FormatResultsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/formatResults/
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 10
      MemorySize: 128

  # Step Functionsの定義
  DataProcessingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/data_processing.asl.json
      DefinitionSubstitutions:
        ConvertToJSTFunctionArn: !GetAtt ConvertToJSTFunction.Arn
        CalculateTimeDifferenceFunctionArn: !GetAtt CalculateTimeDifferenceFunction.Arn
        FormatResultsFunctionArn: !GetAtt FormatResultsFunction.Arn
      Role: 
        Fn::GetAtt: 
          - DataProcessingStateMachineRole
          - Arn

  # Step Functions用のIAMロール
  DataProcessingStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaRole'

Outputs:
  DataProcessingStateMachine:
    Description: "時刻変換と日付計算 State Machine ARN"
    Value: 
      Ref: DataProcessingStateMachine

